apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/carlories/frontend:v4
          resources:
            requests:
              memory: "1Gi"
              cpu: "300m"
            limits:
              memory: "2Gi"
              cpu: "400m"
          env:
            - name: BACKEND_HOST
              value: "backend-service"
            - name: BACKEND_PORT
              value: "80"